apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: default
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/postgresql"