apiVersion: v1
kind: Service
metadata:
  name: my-postegres-service
  namespace: default
spec:
  selector:
    app: postgres
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: my-postgres-service
    protocol: TCP
    port: 5498
    targetPort: 5432
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.